apiVersion: v1
kind: Service
metadata:
  name: auth-frontend
spec:
  type: NodePort
  selector:
    app: auth-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: user-frontend
spec:
  type: NodePort
  selector:
    app: user-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-frontend
spec:
  type: NodePort
  selector:
    app: gateway-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
