apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox:1.28
        command: ['sh', '-c', 'until nc -z postgres 5432; do echo "Waiting for PostgreSQL"; sleep 2; done;']
      containers:
      - name: auth-service
        image: eline2016/backend-auth-service:latest
        ports:
        - containerPort: 3001
        env:
        - name: USER_SERVICE_URL
          value: "http://user-service:3002"
        - name: NODE_ENV
          value: "production"
        - name: DB_HOST
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_NAME
          value: "education"
        startupProbe:
          httpGet:
            path: /  # Ou /health si vous l'ajoutez
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /  # Ou /health si vous l'ajoutez
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 3001        # Port interne du service
      targetPort: 3001  # Port du conteneur
      nodePort: 30011   # NodePort exposé sur le cluster
