apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-frontend
  template:
    metadata:
      labels:
        app: user-frontend
    spec:
      containers:
      - name: user-frontend
        image: eline2016/frontend-user-frontend:latest
        env:
        - name: API_URL
          value: "http://api-gateway"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: user-frontend
spec:
  type: NodePort
  selector:
    app: user-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30022
