FROM node:20-alpine as builder

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install -g @angular/cli@17.1.0
RUN npm install
COPY . .
RUN ng build

FROM node:20-alpine

WORKDIR /app
RUN npm install -g http-server
COPY --from=builder /app/dist/your-project-name /app/dist
EXPOSE 4400
CMD ["http-server", "dist", "-p", "4200"]