apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-frontend
  template:
    metadata:
      labels:
        app: auth-frontend
    spec:
      containers:
        - name: auth-frontend
          image: eline2016/frontend-auth-frontend:latest
          env:
            - name: API_URL
              value: "http://api-gateway:3000"
          ports:
            - containerPort: 80
